cmake_minimum_required(VERSION 3.22)

add_library(components INTERFACE)

file(GLOB COMPONENT_SRC_FILES ${CMAKE_CURRENT_SOURCE_DIR}/*.c
${CMAKE_CURRENT_SOURCE_DIR}/log/*.c
${CMAKE_CURRENT_SOURCE_DIR}/SHT3x/*.c 
${CMAKE_CURRENT_SOURCE_DIR}/ch224/*.c 
${CMAKE_CURRENT_SOURCE_DIR}/relay/*.c 
${CMAKE_CURRENT_SOURCE_DIR}/ws2812/*.c 
${CMAKE_CURRENT_SOURCE_DIR}/SSD1306/*.c
)
target_sources(components INTERFACE ${COMPONENT_SRC_FILES})

target_include_directories(components INTERFACE 
${CMAKE_CURRENT_SOURCE_DIR}/log
${CMAKE_CURRENT_SOURCE_DIR}/SHT3x
${CMAKE_CURRENT_SOURCE_DIR}/ch224
${CMAKE_CURRENT_SOURCE_DIR}/relay
${CMAKE_CURRENT_SOURCE_DIR}/ws2812
${CMAKE_CURRENT_SOURCE_DIR}/SSD1306
)


